### ISSUE TITLE
打不开？

### ISSUE THREAD

**Issue by talent0819** [qxwlmz/aixue#5]
安装之后首页出现auto.js然后闪退

**Comment by qxwlmz** [comment]
软件默认会退一下，打开需要等上一会，你可以把软件强行停止重新打开试试。

**Comment by talent0819** [comment]
还是会无限闪退




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qxwlmz/aixue"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月14日(星期六) 中午12:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qxwlmz/aixue] 打不开？ (#5)





 
软件默认会退一下，打开需要等上一会，你可以把软件强行停止重新打开试试。

**Comment by qxwlmz** [comment]
有Telegram么，方便具体了解下情况吗？

**Comment by talent0819** [comment]
有的，怎么添加您呢？


从 Windows 版邮件发送

发件人: Myue
发送时间: 2021年8月14日 12:55
收件人: qxwlmz/aixue
抄送: talent0819; Author
主题: Re: [qxwlmz/aixue] 打不开？ (#5)

有Telegram么，方便具体了解下情况吗？

**Comment by qxwlmz** [comment]
[Telegram](https://t.me/qxwlmz)
